name: MegaNicks
version: '${project.version}'
main: ir.jeykey.meganicks.MegaNicks
authors: [ Alijk ]
description: Simple powerful Nick plugin
website: https://jeykey.ir
commands:
  streamermode:
    description: Toggle nick command
    usage: /<command> (player)
    aliases:
      - nicks
permissions:
  meganicks.use:
    description: Toggle nick command permission
    default: op